### PR TITLE
removes returning `this` in constructor

### PR DESCRIPTION
**Pull request by pflannery**
- sets dependencies to use const
- renames Interface class to BaseEventEmitter
- removes rest arguments from super calls to EventEmitter

### CODE REVIEW

**Comment by pflannery** [comment]
When running the tests only issue 17 failed for me on Windows. 

I originally had trouble looking at the heap but that was fixed in the last commit. 
When I run my 10000 profile test it's a massive reduction in memory, I see around 50-60MB in process which is a HUGE cut.

**Comment by balupton** [comment]
Looks good. Questions:

- why was util changes to a class? It's strange as the class never needs to be instantiated
- why is was export introduced? we accomplished that already by static getters of Task and TaskGroup inside the TaskGroup class
- Which editor do you use?

**Comment by balupton** [comment]
I'm not sure how this could cause such a dramatic memory reduction, any idea?

**Comment by pflannery** [comment]
Sorry I had originally everything split all the classes in to files i.e. Task, TaskGroup, Helpers and BaseEventEmitter..but when I tried to compile them all in to one library file I ran in to awkward problems between imports and npm requires.
When I made the split my habit of creating singleton objects as classes with static methods was just to make it more obvious of its intention. I will revert it back.
 
I will revert back the exports too, although I think its better to use the ES6 export because then we can ```import {TaskGroup, Task} from 'taskgroup'```

**Comment by pflannery** [comment]
>Which editor do you use?

Web Storm

>I'm not sure how this could cause such a dramatic memory reduction, any idea?

I wonder if it was because of the coffee script leakage I [found](https://github.com/jashkenas/coffeescript/issues/3236#issuecomment-85102994)?

**Comment by pflannery** [comment]
cleared hounds nits.
rebased to one commit.

**Comment by balupton** [comment]
Ignore the hound stuff.

**Comment by balupton** [comment]
I've disabled hound for everything, we should include linting in `cake test`

**Pull request merged**
